# Generated by Django 5.1.3 on 2024-11-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
                ("email", models.EmailField(max_length=100)),
                ("admission_date", models.DateField()),
                ("fee", models.FloatField()),
            ],
        ),
    ]
