# Generated by Django 5.1.3 on 2024-11-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0002_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_date",
            field=models.DateField(null=True),
        ),
    ]
